### ISSUE TITLE
What to do here?

### ISSUE THREAD

**Issue by Reptorian1125** [0xC0000054/gmic-sharp#1]
I opened .sln file, and I got this:

![image](https://user-images.githubusercontent.com/20409297/100764798-bf3d3c00-33c4-11eb-8809-602dabfc0df0.png)

Other than that, it builds apparently.

**Comment by 0xC0000054** [comment]
This project (and gmic-sharp-pdn) use [Sandcastle Help file Builder](https://github.com/EWSoftware/SHFB) to build the documentation.
As you have discovered it is not required to build the DLL, but VS will complain about the unknown project type.

I will update the read-me with a section on building the library.
